# Reinforcement Learning

### Abstract 

Reinforcement Learning is a type of machine learning technique that enables an agent to learn in an interactive environment by trial and error using rewards from its own actions and experiences by interacting with the environment that the agent is in.

The purpose of this project is to train an agent to play the game called Frozen Lake using Q-Learning and we will get a play back of how the agent plays the game after it is trained.

#### The story of Frozen Lake 

##### Winter is here. You and your friends were tossing around a frisbee at the park when you made a wild throw that left the frisbee out in the middle of the lake. The water is mostly frozen, but there are a few holes where the ice has melted. If you step into one of those holes, you'll fall into the freezing water. At this time, there's an international frisbee shortage, so it's absolutely imperative that you navigate across the lake and retrieve the disc. However, the ice is slippery, so you won't always move in the direction you intend. The surface is described using a grid like the following

<h5> SFFF<br>
FHFH <br>
FFFH <br>
HFFG</h5>

This grid is our environment where S is the agent’s starting point, and it’s safe. F represents the frozen surface and is also safe. H represents a hole, and if our agent steps in a hole in the middle of a frozen lake, well, that’s not good. Finally, G represents the goal, which is the space on the grid where the prized frisbee is located.

The agent can navigate left, right, up, and down, and the episode ends when the agent reaches the goal or falls in a hole. It receives a reward of one if it reaches the goal, and zero otherwise.

<h4> Steps followed in this project</h4>

<h6> 1. Setting up the environment </h6>

We will set up the environment, we just call gym.make() and pass a string of the name of the environment we want to set up. Here it is "FrozenLake-v0".

<h6> 2. Creating the Q-table </h6>

We will create the Q-table and initialize the Q- values to zero for each state action pair. The number of rows is equivalent to size of the state space and the number of columns is equivalent to the size of action space.

<h6> 3. Initializing Q-learning parameters </h6>

a. We will initialize e baseline model by the q-learning parameters<br>
b. We will use baseline model provided by TA <br>
c. We will tune the parameters

<h6> 4. We will train the agent and check the rewards </h6>
We will calculate the rewards after each 1000 episode and see how the agent learns from the state action pair and tries to get the maximum rewards
<h6> 5. We will see how the agent plays withe the best hyper parameters </h6>

We will wrap this by making the agent play the Frozen Lake game and run it for 3 episodes to see the result


In [35]:
#importing necessary packages needed for this project
import numpy as np
import gym
import random
import time
from IPython.display import Image
from IPython.display import clear_output

In [36]:
# Getting the Frozen Lake environment where our agent will be trained and perform
env = gym.make("FrozenLake-v0")

In [37]:
#declaring the state and action space
action_space_size = env.action_space.n
state_space_size = env.observation_space.n
#Initializing out Q-Table with all zeroes. We will update the Q-Table after each action performed by the agent
q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [38]:
#Creating a model to train the agent. This will be the baseline model for the Frozen Lake environment
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001


In [48]:
rewards_all_episodes = []
for episode in range(num_episodes):
    state = env.reset()

    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode): 
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:]) 
        else:
            action = env.action_space.sample()
        new_state, reward, done, info = env.step(action)

        # Update Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
            learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))

        state = new_state
        rewards_current_episode += reward 

        if done == True: 
            break

    # Exploration rate decay
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)

    rewards_all_episodes.append(rewards_current_episode)


# Calculate and print the average reward per thousand episodes
rewards_per_thosand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thosand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

********Average reward per thousand episodes********

1000 :  0.06700000000000005
2000 :  0.21000000000000016
3000 :  0.4090000000000003
4000 :  0.5460000000000004
5000 :  0.6680000000000005
6000 :  0.6510000000000005
7000 :  0.6740000000000005
8000 :  0.6540000000000005
9000 :  0.6850000000000005
10000 :  0.6580000000000005


### Part 1

##### Baseline Performance Analysis: -
1. The baseline performace was measured against the baseline model that we have defined in the above cells.
   The agent was able to get more rewards when it was trained on more times. We kept the maximum number of episodes to be 10000    and maximum steps per episode to be 100. In this state the agent was able to get 67 rewards out of first 1000 episodes and      658 rewards on the last 1000 episodes.
2. State : "4x4": [
        "SFFF",
        "FHFH",
        "FFFH",
        "HFFG"
    ]
    
    Action : LEFT = 0 DOWN = 1 RIGHT = 2 UP = 3  
    Reward : 1 - If reaches the goal, 0 - Otherwise
3. We chose the learning rate to be 0.1 and discount to be 0.9. <br>
   Learning Rate - 0.1 - We want the Q-Table to update slowly and the Agent learns slowly as we have kept the number of episodes    as 10000 which is pretty large. <br>
   Discount Factor - 0.9 - We want the agent to consider the future reward rather than focussing on the immediate rewards. 

##### Now lets change the learning rate and the discount factor and see how the rewards change for the agent

In [58]:
#Changing the alpha and Gamma i.e the learning Rate and the discount factor and assessing how tha agent plays
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.3 # alpha
discount_rate = 0.8 # gamma

exploration_rate = 1 # epsilon
max_exploration_rate = 1 #max epsilon
min_exploration_rate = 0.01 #min epsilon
exploration_decay_rate = 0.001 

In [59]:
rewards_all_episodes = []
for episode in range(num_episodes):
    state = env.reset()

    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode): 
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:]) 
        else:
            action = env.action_space.sample()
        new_state, reward, done, info = env.step(action)

        # Update Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
            learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))

        state = new_state
        rewards_current_episode += reward 

        if done == True: 
            break

    # Exploration rate decay
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)

    rewards_all_episodes.append(rewards_current_episode)


# Calculate and print the average reward per thousand episodes
rewards_per_thosand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thosand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

********Average reward per thousand episodes********

1000 :  0.03300000000000002
2000 :  0.09200000000000007
3000 :  0.09800000000000007
4000 :  0.17500000000000013
5000 :  0.2580000000000002
6000 :  0.20100000000000015
7000 :  0.3090000000000002
8000 :  0.33800000000000024
9000 :  0.35800000000000026
10000 :  0.3110000000000002


##### Performance Analysis after tweak: -

1. We changed the alpha (learning Rate) and gamma (discount factor) and trained the agent. The rewards changed drastically. <br>
   As the learning rate is changed from 0.1 to 0.3 the agent started learning fast and as the discount is changed from 0.9 to      0.8 it started focussing on the immediate rewards more than future, so the rewards gained in the initial trainings were more    than the changes in the rewards in the later trainings.<br>
2. The starting epsilon is kept fixed at 0.01 and the max epsilon is 1 which are just the bounds for the epsilon which is          1 i.e (100%) because we should be certain that our agent will start exploring the environment.<br>
   The decay rate (exploitation) is set as low as possible to 0.001, so that we want to make sure that the agent will stick to      explore the environment rather than exploiting i.e. not choosing the action depending on the highest Q- value rather than        randomly choosing action and exploring what happens in the environment.<br>
3. Average number of steps taken per episode - We will calculate that when we see our agent play in the next step.<br>
4. Q-Learning is the value based iteration because we choose the action that determines the maximum rewards. <br>

##### We will now use the baseline provided and determine how the agent beaves

In [62]:
# Using the Baseline model provided for training the agent
total_episodes = 5000
total_test_episodes = 100
max_steps = 99
alpha= 0.7 # Learning rate
gamma = 0.8 # Discounting rate
epsilon = 1.0 # Exploration rate
decay_rate = 0.01 # Exponential decay rate


## Assigning the given baseline to our variable

num_episodes = total_episodes
max_steps_per_episode = max_steps

learning_rate = alpha
discount_rate = gamma

exploration_rate = epsilon
max_exploration_rate = epsilon*1
min_exploration_rate = epsilon * 0.01
exploration_decay_rate = decay_rate

In [63]:
rewards_all_episodes = []
for episode in range(num_episodes):
    state = env.reset()

    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode): 
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:]) 
        else:
            action = env.action_space.sample()
        new_state, reward, done, info = env.step(action)

        # Update Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
            learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))

        state = new_state
        rewards_current_episode += reward 

        if done == True: 
            break

    # Exploration rate decay
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)

    rewards_all_episodes.append(rewards_current_episode)


# Calculate and print the average reward per thousand episodes
rewards_per_thosand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thosand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

********Average reward per thousand episodes********

1000 :  0.20800000000000016
2000 :  0.32800000000000024
3000 :  0.34600000000000025
4000 :  0.2710000000000002
5000 :  0.35700000000000026


#### Hyper-parameters tuning
We will now tune the hyper parameter by tuning the alpha, gamma, epsilon, decay rate and the number of episodes

In [76]:
num_episodes = 10000
max_steps_per_episode = 200

learning_rate = 0.1 # alpha
discount_rate = 0.99 # gamma

exploration_rate = 1 # epsilon
max_exploration_rate = 1 #max epsilon
min_exploration_rate = 0.01 #min epsilon
exploration_decay_rate = 0.001 

In [77]:
rewards_all_episodes = []
for episode in range(num_episodes):
    state = env.reset()

    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode): 
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:]) 
        else:
            action = env.action_space.sample()
        new_state, reward, done, info = env.step(action)

        # Update Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
            learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))

        state = new_state
        rewards_current_episode += reward 

        if done == True: 
            break

    # Exploration rate decay
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)

    rewards_all_episodes.append(rewards_current_episode)


# Calculate and print the average reward per thousand episodes
rewards_per_thosand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thosand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

********Average reward per thousand episodes********

1000 :  0.046000000000000034
2000 :  0.21300000000000016
3000 :  0.44500000000000034
4000 :  0.5750000000000004
5000 :  0.6170000000000004
6000 :  0.6950000000000005
7000 :  0.6860000000000005
8000 :  0.6890000000000005
9000 :  0.6990000000000005
10000 :  0.6820000000000005


#### Evaluation of the model - Making Agent Play

Now we have trained our agent and tweaked the hyper parameters to find out the best reward the agent can generate. <br><br>
As we have already stated that the agent will try to get the maximum rewards and try to reach the goal in less numebr of steps. <br><br>
##### Now lets see how the agent plays the Frozen Lake game.

In [79]:
# Watch our agent play Frozen Lake by playing the best action 
# from each state according to the Q-table

for episode in range(3):
    # initialize new episode params
    state = env.reset()
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)

    for step in range(max_steps_per_episode):        
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)

        action = np.argmax(q_table[state,:])        
        new_state, reward, done, info = env.step(action)

        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                # Agent reached the goal and won episode
                print("****You reached the goal!****")
                print("Number of steps taken ",step)
                time.sleep(3)
            else:
                # Agent stepped in a hole and lost episode     
                print("****You fell through a hole!****")
                print("Number of steps taken ",step)
                time.sleep(3)
            clear_output(wait=True)
            
            break

        # Set new state
        state = new_state

env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG
****You reached the goal!****
Number of steps taken  32


### Conclusion

So we have trained our agent with baseline parameters and then tuned the hyper parameters.
We have thenmade the agent play the Frozen Lake and then captured the result. We can see that the agent has learned the game well enough to play the game and in our test run it has successfully reached the goal within 32 steps.
So we can say that the agent learned to play the game from his action and the rewards that he receined after making the correct move and reaching the goal.

### Citation

1. https://github.com/openai/gym/blob/master/gym/envs/toy_text/frozen_lake.py
2. https://github.com/openai/gym
3. https://deeplizard.com/learn/video/QK_PP_2KgGE


### License

Copyright 2020 ANURAG DHAR

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.